### ISSUE TITLE
Missing djed/__init__.py

### ISSUE THREAD

**Issue by Preston-Landers** [djedproject/djed.static#2]
Using djed.static == 0.4 installed with Pip, and a Pyramid config line like:
```
config.include('djed.static') 
```
I get ```ImportError: No module named 'djed'```. 

If I manually create a blank ```djed/__init__.py``` in site-packages then everything works, because djed is recognized as a package. Is this intentional? Thanks.

**Comment by sidloki** [comment]
Yes, that's intentional. With version 0.4, `djed.static` is a namespace package, as defined in [PEP-0420](https://www.python.org/dev/peps/pep-0420/). Thus,  `djed/__init__.py` is no longer needed, but python >= 3.3 is now required.

Maybe I should mention this requirement somewhere.

**Comment by sidloki** [comment]
I've added a dependencies section to the documentation and the README, to mention python 3.3 requirement.
